adding header and some UI for all products page
sonia-ko/shop-project pull request #1
Opened 2021-10-28 14:59 UTC by sonia-ko

2021-10-29 08:54 UTC, Yuliia143 requested changes

2021-10-29 08:54 UTC, Yuliia143 commented on src/App.tsx
> +import Contacts from "./components/header/contacts/ContactsComponent";
Remove unused import

2021-10-29 08:54 UTC, Yuliia143 commented on src/App.tsx
> +              <React.Fragment>
Remove unneeded Fragment

2021-10-29 08:54 UTC, Yuliia143 commented on src/components/header/productsMenu/ProductsMenu.module.css
> +.productsMenu ul li select option {
Fix selectors

2021-10-29 08:54 UTC, Yuliia143 commented on src/components/header/productsMenu/ProductsMenu.tsx
> +  console.log(productCategories);
Remove all console logs

2021-10-29 16:15 UTC, sonia-ko commented on src/App.tsx
> +import Contacts from "./components/header/contacts/ContactsComponent";
Fixed, thank you.

2021-10-29 16:15 UTC, sonia-ko commented on src/components/header/productsMenu/ProductsMenu.module.css
> +.productsMenu ul li select option {
Done, thank you.

2021-10-29 16:16 UTC, sonia-ko commented on src/components/header/productsMenu/ProductsMenu.tsx
> +  console.log(productCategories);
Removed, thank you

2021-11-01 09:45 UTC, Yuliia143 commented on src/Root.tsx
> +type Props = {};
Remove empty type

2021-11-01 09:45 UTC, Yuliia143 commented on src/components/header/HeaderComponent.tsx
> +        <Contacts></Contacts>
Fix empty tag

2021-11-01 09:45 UTC, Yuliia143 commented on src/components/header/contacts/ContactsComponent.tsx
> +          Chat with us
Add Link

2021-11-01 09:45 UTC, Yuliia143 commented on src/components/header/mainMenu/MainMenu.tsx
> +          About Us
Add Link*2

2021-11-01 10:17 UTC, sonia-ko commented on src/Root.tsx
> +type Props = {};
Done, thanks :)

2021-11-01 10:17 UTC, sonia-ko commented on src/components/header/HeaderComponent.tsx
> +        <Contacts></Contacts>
Fixed, thank you

2021-11-01 10:17 UTC, sonia-ko commented on src/components/header/contacts/ContactsComponent.tsx
> +          Chat with us
Added, thanks

2021-11-01 10:17 UTC, sonia-ko commented on src/components/header/mainMenu/MainMenu.tsx
> +          About Us
Done, thank you

2021-11-01 11:29 UTC, Yuliia143 approved these changes

2021-11-01 11:43 UTC, sonia-ko commented
Merged

2021-11-01 11:50 UTC, merged